
project_id = "xfhsnzqpuaxvkkulehkg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lovable.dev", "https://preview.lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[functions.cpx-postback]
verify_jwt = false
