// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfhsnzqpuaxvkkulehkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmaHNuenFwdWF4dmtrdWxlaGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTUzNzEsImV4cCI6MjA2ODQ5MTM3MX0.tkcsir0_RAK-AkTUXz8bCaHXEdsI6WOkud5YHtVfrUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});